### ISSUE TITLE
Provide Dockerfile for smoother CI/CD

### ISSUE THREAD

**Issue by comradelemoncake** [alsiola/pm2-explorer#8]
Per #3 I think it would be prudent to provide a dockerfile to containerize the app and allow for smoother testing and deployment.

**Comment by alsiola** [comment]
Do you mean a Dockerfile to create a CI environment container in which tests/builds can run? E.g. one with `vsce` installed globally?

If so, then this would require a different CI provider as Travis doesn't support this. I think CircleCI do. I'm not averse to making this change.

**Comment by comradelemoncake** [comment]
Here's what I was referring to.

https://docs.travis-ci.com/user/docker/

**Comment by alsiola** [comment]
I might be missing something here, but I'm not certain how that would work and what advantages it would bring?

**Comment by comradelemoncake** [comment]
Well, I'm not quite sure about your project specifically, but Docker allows you to run your tests in containers and isolate them in development and deployment. 

And with a CI platform, they give you a simple way to make testing predictable across multiple platforms by syncing between your testing environment and production. 

Here's a good resource:

https://www.sealights.io/blog/how-to-speed-up-your-testing-cycle-with-containers/
